#:schema node_modules/wrangler/config-schema.json
name = "workers-assets-test-docusaurus"
compatibility_date = "2024-08-21"

main = "worker.js"
experimental_assets = { directory = "./build", binding = "ASSETS" }
